/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AtcStream: typeof import('./src/components/blog/AtcStream.vue')['default']
    Blog: typeof import('./src/components/Blog.vue')['default']
    Carbon: typeof import('./src/components/blog/Carbon.vue')['default']
    Certs: typeof import('./src/components/Certs.vue')['default']
    CityToll: typeof import('./src/components/blog/CityToll.vue')['default']
    ClimateForecast: typeof import('./src/components/blog/ClimateForecast.vue')['default']
    ClimateGlobe: typeof import('./src/components/blog/ClimateGlobe.vue')['default']
    ClimatePathways: typeof import('./src/components/blog/ClimatePathways.vue')['default']
    Cognac: typeof import('./src/components/blog/Cognac.vue')['default']
    Consensus: typeof import('./src/components/blog/Consensus.vue')['default']
    copy: typeof import('./src/components/blog/RailRadar copy.vue')['default']
    CV: typeof import('./src/components/CV.vue')['default']
    HeadlineUpperText: typeof import('./src/components/blog/components/base/HeadlineUpperText.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Intro: typeof import('./src/components/Intro.vue')['default']
    LineChart: typeof import('./src/components/blog/components/base/LineChart.vue')['default']
    ProjectHeadline: typeof import('./src/components/blog/components/base/ProjectHeadline.vue')['default']
    RailRadar: typeof import('./src/components/blog/RailRadar.vue')['default']
    References: typeof import('./src/components/References.vue')['default']
    RollingTimeline: typeof import('./src/components/blog/RollingTimeline.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkillTree: typeof import('./src/components/blog/components/SkillTree.vue')['default']
    Text: typeof import('./src/components/blog/components/base/Text.vue')['default']
    Toolbar: typeof import('./src/components/blog/components/base/Toolbar.vue')['default']
  }
}
