/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AtcStream: typeof import('./src/components/blog/AtcStream.vue')['default']
    Blog: typeof import('./src/components/Blog.vue')['default']
    BlogLayout: typeof import('./src/components/BlogLayout.vue')['default']
    BlogList: typeof import('./src/components/BlogList.vue')['default']
    Carbon: typeof import('./src/components/blog/Carbon.vue')['default']
    Certs: typeof import('./src/components/Certs.vue')['default']
    Chatbot: typeof import('./src/components/Chatbot.vue')['default']
    CityToll: typeof import('./src/components/blog/CityToll.vue')['default']
    ClimateForecast: typeof import('./src/components/blog/ClimateForecast.vue')['default']
    ClimateGlobe: typeof import('./src/components/blog/ClimateGlobe.vue')['default']
    ClimatePathways: typeof import('./src/components/blog/ClimatePathways.vue')['default']
    Cognac: typeof import('./src/components/blog/Cognac.vue')['default']
    Consensus: typeof import('./src/components/blog/Consensus.vue')['default']
    CV: typeof import('./src/components/CV.vue')['default']
    Intro: typeof import('./src/components/Intro.vue')['default']
    RailRadar: typeof import('./src/components/blog/RailRadar.vue')['default']
    References: typeof import('./src/components/References.vue')['default']
    RollingTimeline: typeof import('./src/components/blog/RollingTimeline.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
